server:
  port: 8081
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:postgresql://localhost:54322/pastebin
    username: admin
    password: password
  security:
    oauth2:
      client:
        registration:
          backend-clients:
            client-id: backend-clients
            client-secret: aW3Kv8sJqEBqofT19xBsjHPyCiP0i7GT
            scope: openid, profile, roles
            authorization-grant-type: client_credentials
        provider:
          backend-clients:
            issuer-uri: http://localhost:8282/realms/pastebin
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8282/realms/pastebin/protocol/openid-connect/certs

minio:
  endpoint: http://localhost
  port: 9000
  key:
    access: ICXvqKor7HKIsXm5MUhj
    secret: dGG3c2MaAPaABagTo3IBOjC2zzYXt8mc3Dg87GAk
  bucket:
    name: pastebin-bucket
  folders:
    bin: bin/

springdoc:
  packagesToScan: mark1708.com.pastebin
  show-actuator: true
  api-docs:
    path: /api/v1/docs/api-docs
  swagger-ui:
    path: /api/v1/docs/swagger-ui.html

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management/actuator
      exposure:
        include: "health,info,prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
logging:
  level:
    com.elementsoft: DEBUG

token:
  converter:
    principal-attribute: preferred_username
    resource-id: pastebin